#define N_BUG        "\uf188"   /*     */
#define N_C          "\ue61e"   /*     */
#define N_CLOVER     "\ufd14"   /*  ﴔ   */
#define N_CODE       "\uf121"   /*     */
#define N_DESKTOP    "\uf6c3"   /*     */
#define N_FIREFOX    "\uf269"   /*     */
#define N_FOLDER     "\uf07c"   /*     */
#define N_FREEBSD    "\uf30c"   /*     */
#define N_GIT        "\uf1d3"   /*     */
#define N_GLOBE      "\uf0ac"   /*     */
#define N_JAVASCRIPT "\ue74e"   /*     */
#define N_LINUX      "\ue712"   /*     */
#define N_MOZILLA    "\ue786"   /*     */
#define N_PYTHON     "\ue73c"   /*     */
#define N_SKYPE      "\uf17e"   /*     */
#define N_TERMINAL   "\uf120"   /*     */
#define N_VIM        "\ue7c5"   /*     */
